# Generated by Django 4.2.2 on 2023-06-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookingshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='video_url',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
