# Generated by Django 4.2.2 on 2023-07-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookingshow', '0002_alter_show_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='video_url',
        ),
    ]
